pages/Terms Of Use.md, pages/contact-us.md
=> Update file: contact-us.md

_school-information/Staff List.md
=> main background  return to original

_school-information/Form Teachers 2023.md, _school-information/Staff List.md
Email address change from @schools.gov.sg to @moe.edu.sg
Please review and approve it. Thanks
=> Email address change from @schools.gov.sg to @moe.edu.sg

_cognitive/Aesthetics/Organisation Chart.md, _school-information/Form Teachers 2023.md
missing 1 Email address change from @schools.gov.sg to @moe.edu.sg 
Please approve . Thanks
=> missing 1 Email address change from @schools.gov.sg to @moe.edu.sg 

_affective/Character and Citizenship Edu/Sexuality Education.md, _school-information/Form Teachers 2023.md
Please check and approve.
Thanks
=> Change chow Kai loon to 4E FT instead of 4C

_school-information/Staff List.md
Please review and approve. Thanks
=> updated Mark Leon Emaill address

_school-information/Staff List.md
=> Mdm Chui Yuen Phun's email address is not formatted

_school-information/Form Teachers 2023.md
Please review and approve. Thanks
=> Added Koay Guimei in 1A form teacher

_co-curricular-activities-ccas/Clubs/Public Address Club.md, _co-curricular-activities-ccas/Clubs/Robotics Club.md, _for-parents/Calendar of Events/School Term (Info from MOE).md, _for-parents/collection.yml, _for-students/School Library/Events & Highlights.md, _for-students/Tinker Friends.md, _for-students/collection.yml, _our-people/School Executive Committee.md
=> PA, Robotic

_about-us/Principal's Foreword.md
Dear Benedict
Please approve again.
Thanks
=> Principal's Foreword 

_for-parents/Admin Matters/Forms.md, _for-staff/Useful Links.md, _our-programmes/Character & Citizenship/Citizenship Programme.md, pages/Ben Test.md
=> removed the 2 broken links

_our-people/Form Teachers by Level.md, _our-people/Teachers by Departments.md
=> removed Mr Richard Goh

_our-people/Form Teachers by Level.md
=> updated form teachers

_co-curricular-activities-ccas/Clubs/Art Club.md, _co-curricular-activities-ccas/Clubs/Chess Club.md, _co-curricular-activities-ccas/Clubs/Choir.md, _co-curricular-activities-ccas/Clubs/EcoMaker Club.md, _co-curricular-activities-ccas/Clubs/Guitar Ensemble.md, _co-curricular-activities-ccas/Clubs/Infocomm Media Club.md, _co-curricular-activities-ccas/Clubs/Public Address Club.md, _co-curricular-activities-ccas/Clubs/Robotics Club.md, _co-curricular-activities-ccas/Clubs/String Ensemble.md, _co-curricular-activities-ccas/Clubs/Synergy.md, _co-curricular-activities-ccas/Sports/Badminton.md, _co-curricular-activities-ccas/Sports/Basketball.md, _co-curricular-activities-ccas/Sports/Bowling.md, _co-curricular-activities-ccas/Sports/Floorball.md, _co-curricular-activities-ccas/Sports/Football.md, _co-curricular-activities-ccas/Sports/Rugby.md, _co-curricular-activities-ccas/Sports/Swimming.md, _co-curricular-activities-ccas/Sports/Tennis.md, _co-curricular-activities-ccas/Sports/Track and Field.md, _co-curricular-activities-ccas/Uniform Groups/Boys Brigade.md, _co-curricular-activities-ccas/Uniform Groups/Cub Scouts.md
Please review and approve
Thanks
=> CCA updated-Removed "Detail"

_about-us/School Canteen Advertisement.md, _our-people/School Executive Committee.md
=> Deleted Suzana from HOD

_about-us/Board of Governors.md
=> updated Board of Governors

_for-parents/Admin Matters/Forms.md, _our-people/Executive & Admin Staff & School Counsellor.md
=> Added new office staff madam Esther lau, updated form of AOL

_our-programmes/English Language/Programmes.md, _our-programmes/Science/Programmes.md
Dear Benedict
Kindly review and approve
Thanks
=> Removed old teacher Mrs Jovina at our program

_our-people/School Executive Committee.md
=> Updated new VP

_about-us/School Canteen Advertisement.md, _our-people/Form Teachers by Level.md
Please approve my requested.
Many Thanks
=> updated teacher email address

_for-parents/School Publication/ECHO.md, _for-parents/School Publication/School Magazine.md, _our-programmes/Mathematics/Programmes.md
Dear Siok Pheng 
pls approve the website requested.
many Thanks
=> updated Math Dept

_co-curricular-activities-ccas/Clubs/Art Club.md, _co-curricular-activities-ccas/Clubs/Choir.md, _co-curricular-activities-ccas/Clubs/EcoMaker Club.md, _co-curricular-activities-ccas/Clubs/Public Address Club.md, _co-curricular-activities-ccas/Clubs/Robotics Club.md, _co-curricular-activities-ccas/Sports/Bowling.md, _co-curricular-activities-ccas/Sports/Tennis.md, _our-people/Teachers by Departments.md
Pls approve the request. 
Thanks
=> changed to CCA teachers

_for-parents/Vendor/2025 Student Care Centre.md
=> 2025 Student Care Centre updated

_our-programmes/Character & Citizenship/Sexuality Education.md
=> Updated MOE SEXUALITY EDUCATION IN SCHOOLS

_our-programmes/Character & Citizenship/Sexuality Education.md, _our-programmes/Mother Tongue Languages/eComposition.md, _our-programmes/collection.yml
Please review and approval.
Thanks
=> Updated sexuality-education

_about-us/Principal's Foreword.md, _about-us/School History/Gallery.md, _about-us/School History/History of ACS.md, _about-us/Vision, Mission & Values.md, _our-people/Allied Educators.md, _our-people/Executive & Admin Staff.md, _our-programmes/Aesthetics (Art & Music).md, _our-programmes/Character & Citizenship/Citizenship Programme.md, _our-programmes/Character & Citizenship/Education and Career Guidance.md, _our-programmes/Character & Citizenship/Social Studies.md, _our-programmes/Character & Citizenship/Values in Action Programme.md, _our-programmes/English Language/Programmes.md, _our-programmes/Experiential Learning/Internationalisation Programme.md, _our-programmes/Gifted Education/Programmes.md, _our-programmes/Infocomm & Communications/Programmes.md, _our-programmes/Mother Tongue Languages/Chinese Language.md, _our-programmes/Mother Tongue Languages/Tamil Language.md, _our-programmes/Physical Education/Learning for Life (LLP).md, _our-programmes/Physical Education/Programmes.md, _our-programmes/Science/Programmes.md, _our-programmes/Student Management/Student Management Department.md
Dear Benedict
Please approve the website requested.
Many Thanks
=> Update the collected information

_our-people/Form Teachers by Level.md
Hi Benedict
Please approve my requested.
Thanks
=> updated from Vanessa 

_our-people/Teachers by Departments.md
Dear Siok Pheng/Benedict
Many Thanks
=> Teachers' Email updated.

_our-people/Form Teachers by Level.md, _our-people/Teachers by Departments.md
Dear Siok Pheng /Benedict
Please review and approve it ASAP.
Thanks
=> Charmaine requested to change Miss to Ms

_co-curricular-activities-ccas/Clubs/Synergy.md, _co-curricular-activities-ccas/Sports/Badminton.md, _co-curricular-activities-ccas/Sports/Basketball.md, _co-curricular-activities-ccas/Sports/Bowling.md, _co-curricular-activities-ccas/Sports/Floorball.md, _co-curricular-activities-ccas/Sports/Football.md, _co-curricular-activities-ccas/Sports/Tennis.md, _co-curricular-activities-ccas/Uniform Groups/Cub Scouts.md, _for-students/Tinker Friends.md
Dear Siok Pheng/Benedict
Thanks
=> Update requested by Mrs Wan

_about-us/Campus Map.md, _co-curricular-activities-ccas/Sports/Badminton.md, _our-people/Form Teachers by Level.md, _our-people/Teachers by Departments.md
Dear Siok Pheng/Benedict
Pls review and approve it.
Many thanks
=> New form teacher updated

_our-people/Form Teachers by Level.md, _our-people/Teachers by Departments.md
Dear Siok Pheng / Benedict
Please approve it when you are free.
Thanks
=> some of teacher salutations updated

_our-people/Teachers by Departments.md
Dear Siok Pheng / Benedict
Pls approve it ASAP.
Thanks
=> Louis changed from English department to math

_about-us/School Canteen Advertisement.md, _about-us/collection.yml
Dear Siok Pheng/Benedict
i already updated the canteen advertisement in website, please approve ASAP.
Thank you.
=> Updated School Canteen Advertisement

_our-people/School Executive Committee.md
Dear Benedict
Please review and approve it.
Many Thanks
=> Subject Head for Ting Ting

_our-people/School Executive Committee.md
Dear Benedict
I already updated, please approve it 
Many Thanks
=> L/H for Sarah

_about-us/Board of Governors.md, _our-partners/Our Partners.md, _our-people/Form Teachers by Level.md, _our-people/School Executive Committee.md, _our-people/Teachers by Departments.md
Dear Benedict
I've updated the website as follows. 
Kindly review and approve.
1) Christine Ho - remove from our website (SEC and Level)
2) Du Guang - MTL Dept + 1A FT (remove Zhou Lingyu)
3) Ong Ci Yi Rachel - PE Dept + 5C FT (remove Pauline Ho)
4) Panneer Selvam Karuppiah - Mathematics Dept + 6C FT (remove Lim May Chan)
5)Slight reordering - 
A. Mr Koh Yee Lee
B.Mrs Janis Pavia
C. Ms Aubrey Ong
D. Mrs Dawn Wee
E Mrs Heng Xiu Qin
6)OBA that the new site is https://acsoba.org
7) updated board members
Thank you.
=> Updated website for T3

_for-staff/Useful Links.md, _our-people/Form Teachers by Level.md, _our-people/School Counsellor & Special Educational Needs Officer.md, _our-people/Teachers by Departments.md
Dear Benedict
i have updated the website for Useful Links
Please review and Approve it.
Many Thanks
=> Requested by VP, for Useful Links

_for-staff/Useful Links.md
Dear Benedict
I've updated the website with the Useful Links requested by Ernest. 
Please review and approve the update. 
Thank you.
=> Requested by Ernest, for Useful Links(Change Name to Transport Pair Chat Assistant)

_co-curricular-activities-ccas/Sports/Football.md, _our-people/Teachers by Departments.md
Dear Benedict
I've followed up as below for your review and approval:
1.Transfer of Selvam to the SC department.
2.Removal of Divya from the Football CCA.
Many Thanks
=> some changed for Divya, Selvam

_our-people/Form Teachers by Level.md, _our-people/School Executive Committee.md, _our-people/Teacher Leaders Council.md, _our-people/Teachers by Departments.md
Dear Benedict,
I've updated from LHs to Subject Head.
Kindly review and approve the changes.
Many thanks
=> Updated Subject Head

_co-curricular-activities-ccas/Sports/Football.md
Dear Benedict
I have been updated CCA teachers requested by Bavani
Pls review and approve.
Thanks
=> Updated CCA teachers requested by Bavani

_co-curricular-activities-ccas/Clubs/Public Address Club.md, _our-people/Form Teachers by Level.md, _our-people/School Counsellor & Special Educational Needs Officer.md, _our-people/Teachers by Departments.md
Dear Benedict
i have updated accordingly.
Kindly review and approve.
Many Thanks
=> Updated new Teachers in Form Teachers by Level

pages/The ACS(P) Brand of Education.md
Mrs Wan asked me to update 'The ACS(P) Brand of Education' and I have already updated it. Please review and approve.
Many thanks
=> updated "The ACS(P) Brand of Education" requested by Mrs Wan
